[package]
name = "traits-and-structs"
version = "0.1.0"
authors = ["Hunter Jarrell <hunter.jarrell@ufl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
